### ISSUE TITLE
[BUG] Create, update, and retreiving chirps is not working due to state management change

### ISSUE THREAD

**Issue by pranmar123** [Intro-to-SE-Spring-2020/Chirpr#103]
### Details
-  All other features of create, update, and getting chirps are unavailable. This is due to new state management.

### Acceptance Criteria:
- Be able to create, update, and retrieve chirps

### Story Points
Story Points: 2

### Bug
- Critical

**Comment by pranmar123** [comment]
Assigning this to @JustinASmith

**Comment by JustinASmith** [comment]
@pranmar123 Will get on this ASAP.
