### ISSUE TITLE
[DATABASE] connect registration form to database

### ISSUE THREAD

**Issue by pranmar123** [Intro-to-SE-Spring-2020/Chirpr#31]
### Details
-  Connect the registration form to the database
- Create a backend for the registration

### Acceptance Criteria:
-  A registered user is stored in the database. 
- Code is tested and all tests pass. 

Issue relates to epic #19 

### Story Points:
- Story Points: 2

### Risk
- Low risk

**Comment by JustinASmith** [comment]
I wanted to point out. The wording on this issues is not correct. The registration form is connected to Express API.
